# Generated by Django 5.0.2 on 2024-02-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='assignment_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='exam_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='participation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('topic', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('enrolled_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.class')),
            ],
        ),
    ]
